version: '3'
services:
  app:
    container_name: disnayapp
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: mysqldb
    image: mysql:8
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=16jamayca6
